### ISSUE TITLE
Python module

### ISSUE THREAD

**Issue by mbikyaw** [rjeschmi/OpenFreezer#1]
Hi,

I am adding new functionality as require in our lab. I also like API base single page application using bootstrip. 

OpenFreezer use both PHP and Python. New code should be developed in Python? 

Best,
Kyaw

**Comment by rjeschmi** [comment]
Hi,

We are not really working on this project any more as it didn't meet our needs. I will warn you that there are some pretty significant security issues with the code (primarily on the interface between the Python and PHP code).

I would work in whichever language you are most comfortable with, but the OF_app Python flask App was the way I thought looked the best.

Good Luck!

**Comment by mbikyaw** [comment]
Thank @rjeschmi for your kind advice.
